version: "3"
services:
  app:
    image: node:14-alpine
    container_name: react-dev
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    entrypoint: ["npm", "run", "start"]
